### PR TITLE
Pull request for commit after commit             10c0b and before 7e854

### PR DESCRIPTION
**Pull request by Ruth-Seven**
Date:2021-10-04 13:32:19 +0800; Author: ruth-seven; Commit: 7e8548c 
 fix(parser): update log of success

Date:2021-10-04 13:22:51 +0800; Author: ruth-seven; Commit: bd924c9 
 fix(parser): update log quoters

Date:2021-10-04 13:19:31 +0800; Author: ruth-seven; Commit: 11de839 
 fix(parser): update parser parameters

Date:2021-10-04 13:16:14 +0800; Author: ruth-seven; Commit: 5be07ec 
 fix(log): add succes of updating fork

Date:2021-10-04 13:12:59 +0800; Author: ruth-seven; Commit: 7b45cdc 
 fix(log): fix user of remote

Date:2021-10-04 13:12:15 +0800; Author: ruth-seven; Commit: 4c6ed30 
 fix(log): add user of remote

Date:2021-10-04 13:07:48 +0800; Author: ruth-seven; Commit: 1877b67 
 fix(log): add log of create_pr

Date:2021-10-04 13:04:23 +0800; Author: ruth-seven; Commit: 77fe655 
 fix(pull-request): fix missing methodes

Date:2021-10-04 13:02:40 +0800; Author: ruth-seven; Commit: a35ba99 
 feat(pull-request): using property decorate class parmeter

Date:2021-10-04 11:27:46 +0800; Author: ruth-seven; Commit: 41528d2 
 fix(pull_request): clear out the two way of generation

Date:2021-10-04 10:35:46 +0800; Author: ruth-seven; Commit: 650dfda 
 feat(pull_request): judge local remote and refactor with speration of data and procession

Date:2021-10-03 23:51:42 +0800; Author: ruth-seven; Commit: 61452e2 
 fix(pull_request): fix of repo branch

Date:2021-10-03 23:49:12 +0800; Author: ruth-seven; Commit: e7f7863 
 fix(pull_request): fix of filter pr

Date:2021-10-03 23:33:16 +0800; Author: ruth-seven; Commit: 177a10d 
 fix(pull_request): fix bugs of reset_empty

Date:2021-10-03 23:32:07 +0800; Author: ruth-seven; Commit: 33bf975 
 fix(pull_request): fix bugs of generation of title

### CODE REVIEW

**Comment by Ruth-Seven** [comment]
hi, JD. I really you repo about auto-github. So i refactor a lot. Could you please skim over it and give me some advices?

**Comment by Ruth-Seven** [comment]
test?

**Comment by jd** [comment]
This is… big?

**Comment by Ruth-Seven** [comment]
> This is… big?

@jd  Maybe I should write local test to avoid too much commits. 😂

**Pull request closed without merging**
